name: efood_multivendor_restaurant
description: An application for multivendor ecommerce restaurant.
publish_to: 'none'
version: 1.1.4+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  webview_flutter: ^3.0.0

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.0.6
  connectivity: ^3.0.6
  firebase_core: ^1.2.1
  firebase_messaging: ^11.2.4
  flutter_local_notifications: ^9.2.0
  path_provider: ^2.0.2
  url_strategy: ^0.2.0
  shimmer_animation: ^2.0.0
  image_picker: ^0.8.0+4
  http: ^0.13.3
  pin_code_fields: ^7.4.0
  url_launcher: ^6.0.9
  vibration: 1.7.4-nullsafety.0
  audioplayers: ^0.20.1
  flutter_switch: ^0.3.2
  flutter_typeahead: ^4.0.0
  cached_network_image: ^3.2.1
  phone_number:
  #  ^1.0.0
  country_code_picker: ^2.0.2
  flutter_widget_from_html_core: ^0.8.5+3
  bluetooth_thermal_printer: ^0.0.6
  esc_pos_utils: ^1.0.0
  printing: ^5.8.0
  modal_bottom_sheet: ^2.0.1
  geolocator: ^9.0.2
  google_maps_flutter: ^2.1.6
  universal_html: ^2.0.8
  #  get: ^4.6.3
  intl: ^0.17.0

#  blue_thermal_printer: ^1.1.8
#  bluetooth_print: ^3.0.1

dev_dependencies:
  change_app_package_name: ^1.0.0

  flutter_launcher_icons: ^0.10.0


  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/font/
    - assets/font/hacen/
    - assets/language/
    - assets/notification.mp3



  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/font/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/font/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/font/Tajawal-Black.ttf
          weight: 900
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/app_icon.png"
  remove_alpha_ios: true